#        "searxng": {
#            "command": "powershell",
#            "args": [
#                "-command",
#                "(Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/gusbicalho/dockerfiles-public/refs/heads/main/searxng/docker-compose.yml').Content | Out-File -FilePath docker-compose.yml; docker-compose up -d; docker exec -it x-mcp-searxng uv tool run mcp-searxng"
#            ]
#        },
services:
  x-searxng:
    image: searxng/searxng
    container_name: x-searxng
    ports:
      - "9111:8080"
    volumes:
      - ./searxng-data:/etc/searxng
    environment:
      - BASE_URL=http://localhost:9111/
      - INSTANCE_NAME=gus-searxng
    restart: unless-stopped

  x-mcp-service:
    container_name: x-mcp-searxng
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.9-slim
        RUN pip install uv
        uv tool install mcp-searxng
        ENV SEARXNG_URL http://x-searxng:8080
    environment:
      - SEARXNG_URL=http://x-searxng:8080
    depends_on:
      - x-searxng
    restart: unless-stopped
    tty: true
    stdin_open: true
